### ISSUE TITLE
Is there a bug in function "mergeClusters"?

### ISSUE THREAD

**Issue by Caravan0** [yzyuzhang/incremental-dbscan#1]
Thanks for the sharing. But I supposed there is a bug in merge clusters. In line 112 of DBSCANCluster.java, several clusters are merged into cluster NO. clusterGlobalID, however, clusterGlobalID may not contained by the set which contains only non-noise cluster index.

Lines 79 through 86 of DBSCANCluster.java
`
// set contains only non-noise cluster index. 
HashSet<Integer> set = new HashSet<>();
for (Point seed : updateSeed) {
    if (seed.clusterIndex != -1) {
        int rootClusterID = findRootClusterID(seed.clusterIndex);
        set.add(rootClusterID);
    }
}
`

Lines 111 through 112 of DBSCANCluster.java
`
// case 3: seeds contains several clusters, merge them
mergeClusters(updateSeed, points, set, clusterGlobalID);
`

Lines 129 through 137 of DBSCANCluster.java
`
private void mergeClusters(final List<Point> seeds,
        final List<Point> points,
        final HashSet<Integer> set,
        final int id) {
    for (int e : set) {
        clusterMapping.put(e, id);
    }
    clusterMapping.put(id, id);
}
`

**Comment by yuz1988** [comment]
Hi, Caravan0 

Thank you for pointing out. 
The clusterGlobalID is the new cluster ID, which will substitute the merged cluster IDs, that is why I use clusterMapping to record this child-parent relationship, like the union-find tree. So clusterGlobalID actually should not be contained by the set as it is the new one.  
The previous code is just a prototype and now is refactored. 
Please refer to the VLDB 98 paper: Incremental Clustering for Mining in a Data Warehousing Environment. The algorithm inplemented only contains the insertion part.
